export const NovelErrorCode = {
  STAGE_TRANSITION_BLOCKED: "ERR_STAGE_TRANSITION_BLOCKED",
  REQUIRED_REVIEW_MISSING: "ERR_REQUIRED_REVIEW_MISSING",
  REVIEW_ARTIFACT_STALE: "ERR_REVIEW_ARTIFACT_STALE",
  CANON_ACCEPTANCE_REQUIRES_EXPLICIT_ACTION: "ERR_CANON_ACCEPTANCE_REQUIRES_EXPLICIT_ACTION",
  PATH_OUTSIDE_NOVEL_ROOT: "ERR_PATH_OUTSIDE_NOVEL_ROOT",
  PROJECT_NOT_INITIALIZED: "ERR_PROJECT_NOT_INITIALIZED",
  ARTIFACT_CORRUPT: "ERR_ARTIFACT_CORRUPT",
  UNSUPPORTED_CORPUS_FILE_TYPE: "ERR_UNSUPPORTED_CORPUS_FILE_TYPE",
  CORPUS_FILE_TOO_LARGE: "ERR_CORPUS_FILE_TOO_LARGE",
  ARTIFACT_NOT_FOUND: "ERR_ARTIFACT_NOT_FOUND",
} as const

export type NovelErrorCode = typeof NovelErrorCode[keyof typeof NovelErrorCode]

export class NovelError extends Error {
  readonly code: NovelErrorCode

  constructor(code: NovelErrorCode, message: string) {
    super(message)
    this.name = "NovelError"
    this.code = code
  }
}

export const ERR_STAGE_TRANSITION_BLOCKED = NovelErrorCode.STAGE_TRANSITION_BLOCKED
export const ERR_REQUIRED_REVIEW_MISSING = NovelErrorCode.REQUIRED_REVIEW_MISSING
export const ERR_REVIEW_ARTIFACT_STALE = NovelErrorCode.REVIEW_ARTIFACT_STALE
export const ERR_CANON_ACCEPTANCE_REQUIRES_EXPLICIT_ACTION = NovelErrorCode.CANON_ACCEPTANCE_REQUIRES_EXPLICIT_ACTION
export const ERR_PATH_OUTSIDE_NOVEL_ROOT = NovelErrorCode.PATH_OUTSIDE_NOVEL_ROOT
export const ERR_PROJECT_NOT_INITIALIZED = NovelErrorCode.PROJECT_NOT_INITIALIZED
export const ERR_ARTIFACT_CORRUPT = NovelErrorCode.ARTIFACT_CORRUPT
export const ERR_UNSUPPORTED_CORPUS_FILE_TYPE = NovelErrorCode.UNSUPPORTED_CORPUS_FILE_TYPE
export const ERR_CORPUS_FILE_TOO_LARGE = NovelErrorCode.CORPUS_FILE_TOO_LARGE
export const ERR_ARTIFACT_NOT_FOUND = NovelErrorCode.ARTIFACT_NOT_FOUND
